//
// Created by jakub on 21.05.19.
//

#ifndef ARTILLERY_CONSTANTS_H
#define ARTILLERY_CONSTANTS_H

unsigned int WINDOW_WIDTH = 800;
unsigned int WINDOW_HEIGHT = 600;
size_t TERRAIN_POINT_COUNT = 4;
float TERRAIN_POINT_COEFF = float(WINDOW_WIDTH) / float(TERRAIN_POINT_COUNT);

#endif //ARTILLERY_CONSTANTS_H
