#ifndef ARTILLERY_CONSTANTS_H
#define ARTILLERY_CONSTANTS_H

const unsigned int WINDOW_WIDTH = 800;
const unsigned int WINDOW_HEIGHT = 600;
const float CANNON_MAX_FALL_VELOCITY = 0.9f;
const float CANNON_FALL_VELOCITY_INCREMENT = 0.03f;
const float CANNON_MOVE_AMOUNT = 0.5f;
const float MAX_MOVEMENT_ELEVATION = 4;

#endif //ARTILLERY_CONSTANTS_H
